 liste_mots= [
"sèche-cheveux",
"marelle",
"chalumeau",
"la cinquième roue du carosse",
"tutu",
"pack de bières",
"avoir les doigts de pied en éventail",
"jul",
"taupe",
"garde du corps",
"caserne de pompiers",
"salle de bain",
"Egypte",
"serrer la main",
"parabole",
"banque de sang",
"espion",
"baguettes chinoises",
"sardines",
"chinatown",
"pause-café",
"Général de Gaulle",
"écrevisse",
"bowling",
"avocat de justice",
"aspirine",
"dragon",
"vigne",
"roller",
"aspirateur",
"élan",
"aéroport",
"maquillage",
"dentiste",
"dinosaure",
"fromage de chèvre",
"arbitre",
"retour d'ascenseur",
"pied de poule",
"jumeaux",
"vendeur à la sauvette",
"choucroute",
"tarte aux fraises",
"amoureux",
"auto-tamponneuses",
"sandwich au thon",
"oeuf dur",
"zoo",
"sangsue",
"astronaute",
"journée portes-ouvertes",
"mère nature",
"tyrolienne",
"sauterelle",
"frites",
"pollution",
"diplôme",
"clown",
"avocat",
"yoga",
"cage à oiseau",
"vache vampire ailée",
"pilier de bar",
"herse",
"admirateur secret",
"flipper",
"vol d'identité",
"piranha",
"voiture d'occasion",
"cervelle de moineau",
"soirée pyjama",
"se défendre bec et ongle",
"gardien de zoo",
"strip-teaseuse",
"radeau",
"étoiel filante",
"castor",
"jambe cassée",
"gruyère",
"chameau",
"camion de pompier",
"porte-gobelet",
"tsunami",
"soupe à l'oignon",
"enterrement de vie de jeune fille",
"jacuzzi",
"pizza surgelée",
"avoir la tête daans les nuages",
"écoper",
"chapeau de magicien",
"oeuf pourri",
"dos d'âne",
"soulever des montagnes",
"chapeau melon",
"omelette",
"facteur"
];

module.exports = liste_mots;